"""update indexes

Revision ID: 44adfdc38f27
Revises: d30f2d20120d
Create Date: 2026-03-16 13:51:32.998058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44adfdc38f27'
down_revision: Union[str, Sequence[str], None] = 'd30f2d20120d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_index(op.f('ix_categories_section_id'), 'categories', ['section_id'], unique=False)
    op.drop_index(op.f('ix_offer_variants_id'), table_name='offer_variants')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.create_index(op.f('ix_offers_name'), 'offers', ['name'], unique=False)
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_email'), 'orders', ['customer_email'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_email'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_index(op.f('ix_offers_name'), table_name='offers')
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offer_variants_id'), 'offer_variants', ['id'], unique=False)
    op.drop_index(op.f('ix_categories_section_id'), table_name='categories')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    # ### end Alembic commands ###
